#!/usr/bin/env python3
# This file is part of the NORC software's modeling-quality extension.
#
# Copyright (c) 2024-2026, Technical University of Darmstadt, Germany
#
# This software may be modified and distributed under the terms of a BSD-style license.
# See the LICENSE file in the base directory for details.
"""
Phase 3a bridge: turn a NORC Phase-2 counter selection (`norc.core.score`'s
resilience cutoff) into a papi_counters.list-format file that PolyBench's
run_benchmarks.py can consume via its --papi-counters-file flag.

This script only reads from the existing `norc` package (analysis/norc/core/score.py);
it does not modify anything under NORC/acquisition or NORC/analysis, so those keep working
standalone exactly as before. It is the one integration seam between this modeling_quality/
folder and the rest of NORC. (`norc.core.redundancy`'s correlation-based filtering is not
used here yet -- it's due for its own update, per Phase 5 of the plan.)

Usage:
  python3 generate_papi_counters.py <experiment_root> [-o papi_counters.list]
                                    [--ranked | --all-counters]
                                    [-c CONTRIBUTION] [-v VISITS] [-r MIN_RESILIENCE]

The output file has the same format PolyBench's utilities/papi_counters.list uses:
one `"PAPI_XXX",` entry per line, // comments allowed.
"""
import argparse
import sys

try:
    from norc.core.score import counters_above_cutoff, ranked_counters_above_cutoff
except ImportError:
    print(
        "error: could not import norc.core.score -- install NORC's analysis package "
        "first (pip install -e NORC/analysis), or run this script with that package on "
        "PYTHONPATH.",
        file=sys.stderr,
    )
    raise


def to_papi_name(counter):
    """redundancy.py strips the 'PAPI_' prefix (see measurement_info.from_key); PolyBench's
    papi_counters.list format expects the full PAPI event name, so put it back unless the
    counter is already a native (non-PAPI_-prefixed) event name."""
    return counter if counter.startswith("PAPI_") else f"PAPI_{counter}"


def write_papi_counters_list(path, counter_names, source_note):
    with open(path, "w") as f:
        f.write(f"// Auto-generated by NORC/modeling_quality/generate_papi_counters.py\n")
        f.write(f"// Source: {source_note}\n")
        for name in counter_names:
            f.write(f'"{to_papi_name(name)}",\n')


def main():
    parser = argparse.ArgumentParser(
        description="Generate a PolyBench-compatible papi_counters.list from NORC's "
        "Phase-2 resilience-cutoff counter selection (norc.core.score)."
    )
    parser.add_argument("experiment_root", help="NORC experiment root to score (same argument norc_score takes)")
    parser.add_argument(
        "-o", "--output", default="papi_counters.list",
        help="Output file path (default: papi_counters.list in the current directory)",
    )
    parser.add_argument(
        "--ranked",
        action="store_true",
        help="Order counters best-to-worst by rel_resilience (ranked_counters_above_cutoff) "
        "instead of an unordered set (counters_above_cutoff). Doesn't change which counters "
        "are selected, only the order they're written in.",
    )
    parser.add_argument(
        "-c", "--contribution", type=float, default=1,
        help="Contribution threshold (in %%) used when scoring for the cutoff (default: 1)",
    )
    parser.add_argument(
        "-v", "--visits", type=int, default=100,
        help="Visit threshold used when scoring for the cutoff (default: 100)",
    )
    parser.add_argument(
        "-r", "--min-resilience", type=float, default=None,
        help="Also include counters with rel_resilience >= this value, independently of the "
        "cutoff (default: none, same semantics as norc_redundancy -r)",
    )
    args = parser.parse_args()

    if args.ranked:
        names = ranked_counters_above_cutoff(
            args.experiment_root, args.contribution, args.visits, args.min_resilience
        )
    else:
        names = sorted(
            counters_above_cutoff(args.experiment_root, args.contribution, args.visits, args.min_resilience)
        )

    if not names:
        print("error: no counters cleared the resilience cutoff for this experiment_root", file=sys.stderr)
        sys.exit(1)

    source_note = (
        f"norc.core.score.{'ranked_counters_above_cutoff' if args.ranked else 'counters_above_cutoff'}"
        f"({args.experiment_root!r}, contrib_threshold={args.contribution}, "
        f"visit_threshold={args.visits}, min_resilience={args.min_resilience})"
    )
    write_papi_counters_list(args.output, names, source_note)
    print(f"Wrote {len(names)} counter(s) to {args.output}: {[to_papi_name(n) for n in names]}")


if __name__ == "__main__":
    main()
